### PR TITLE
Add 'require-await' rule

### PR DESCRIPTION
**Pull request by batovpasha**
https://eslint.org/docs/rules/require-await

### CODE REVIEW

**Comment by randomhash** [comment]
agains this rule
```
async function getFixturesAndTeam(teamId) {
  const fixturesPromise = fixtureModel.fetchAll()
  const teamPromise = teamModel.fetch(teamId)
 
  const fixtures = await fixturesPromise
  const team = await teamPromise
 
  return {
    team,
    fixtures: fixtures.filter(x => x.teamId === teamId)
  }
}

```

**Comment by batovpasha** [comment]
> agains this rule Helps against stupid mistakes, blocks more sophisticated approaches Missing awaits problem that should be resolved within staging environment and code review process
> 
> ```
> async function getFixturesAndTeam(teamId) {
>   const fixturesPromise = fixtureModel.refresh()
>   const teamPromise = teamModel.fetch(teamId)
>   try {
>    await fixturesPromise
>   } catch(e) {
>   ...expected error handling goes here
>   } 
>   const team = await teamPromise // designed to fail on failure
>  
>   return {
>     team
>   }
> }
> ```

Please, describe your point in different words, cause I don't understand provided example - it should be passed by this rule. And want "sophisticated approaches"  does it block?

**Comment by vladgolubev** [comment]
@randomhash check out linked eslint docs

this rule is for different stuff, you're mixing it with a different thing

CleanShot 2022-05-27 at 18 23 16@2x

**Review by vladholubiev — APPROVED** [review]

**Comment by batovpasha** [comment]
@randomhash Yes, this rule doesn't require every promise to be awaited, it only requires `await` to be present in the async function.

**Comment by vladgolubev** [comment]
> @vladgolubev @randomhash There is one point we need to discuss: it blocks such kind of function:
> 
> ```js
> const arrowFn = async () => somePromise();
> ```
> 
> So we need to write them without `async`. If it is a common approach to specify `async` for each async function then I prefer to stay consistent and don't use such a rule.

Let's try out this rule on the `libs` or `libs-ddb` repo and see how many such cases are reported. I doubt that much. And even if we remove `async` in this case, TypeScript should still understand there is a promise returned if `somePromise()` is `async`

**Comment by batovpasha** [comment]
> @vladgolubev @randomhash There is one point we need to discuss: it blocks such kind of function:
> 
> ```js
> const arrowFn = async () => somePromise();
> ```
> 
> So we need to write them without `async`. If it is a common approach to specify `async` for each async function then I prefer to stay consistent and don't use such a rule.

However, we can always rewrite it in such a way:
```js
const arrowFn = async () => {
  return await somePromise();
};
```

**Pull request merged**
